# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{backstage}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobias Crawley"]
  s.date = %q{2011-04-11}
  s.default_executable = %q{backstage}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{tcrawley@gmail.com}
  s.executables = ["backstage"]
  s.extra_rdoc_files = [
    "README.md",
    "TODO"
  ]
  s.files = [
    "Gemfile.lock",
    "README.md",
    "backstage.rb",
    "config.ru",
    "config/torquebox.yml",
    "lib/apps.rb",
    "lib/apps/models/app.rb",
    "lib/apps/routes.rb",
    "lib/authentication.rb",
    "lib/destinations.rb",
    "lib/destinations/models/destination.rb",
    "lib/destinations/models/message.rb",
    "lib/destinations/models/queue.rb",
    "lib/destinations/models/topic.rb",
    "lib/destinations/routes.rb",
    "lib/has_mbean.rb",
    "lib/helpers.rb",
    "lib/jobs.rb",
    "lib/jobs/models/job.rb",
    "lib/jobs/routes.rb",
    "lib/message_processors.rb",
    "lib/message_processors/models/message_processor.rb",
    "lib/message_processors/routes.rb",
    "lib/resource.rb",
    "lib/resource_helpers.rb",
    "lib/services.rb",
    "lib/services/models/service.rb",
    "lib/services/routes.rb",
    "lib/torquebox_managed.rb",
    "lib/util.rb",
    "spec/api_spec.rb",
    "spec/auth_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tobias/backstage}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.1}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/api_spec.rb",
    "spec/auth_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["= 1.1.2"])
      s.add_runtime_dependency(%q<rack-flash>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.0"])
      s.add_runtime_dependency(%q<jmx>, ["= 0.6"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<torquebox>, [">= 0"])
      s.add_runtime_dependency(%q<tobias-sinatra-url-for>, [">= 0"])
      s.add_runtime_dependency(%q<rack-accept>, [">= 0"])
      s.add_development_dependency(%q<thor>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<watchr>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, ["> 0.14"])
      s.add_runtime_dependency(%q<torquebox-rake-tasks>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, ["= 1.1.2"])
      s.add_dependency(%q<rack-flash>, [">= 0"])
      s.add_dependency(%q<haml>, ["~> 3.0"])
      s.add_dependency(%q<jmx>, ["= 0.6"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<torquebox>, [">= 0"])
      s.add_dependency(%q<tobias-sinatra-url-for>, [">= 0"])
      s.add_dependency(%q<rack-accept>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<watchr>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<thor>, ["> 0.14"])
      s.add_dependency(%q<torquebox-rake-tasks>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, ["= 1.1.2"])
    s.add_dependency(%q<rack-flash>, [">= 0"])
    s.add_dependency(%q<haml>, ["~> 3.0"])
    s.add_dependency(%q<jmx>, ["= 0.6"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<torquebox>, [">= 0"])
    s.add_dependency(%q<tobias-sinatra-url-for>, [">= 0"])
    s.add_dependency(%q<rack-accept>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<watchr>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<thor>, ["> 0.14"])
    s.add_dependency(%q<torquebox-rake-tasks>, [">= 0"])
  end
end

